language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - docker-compose up -d

# command to run tests
script:
  - docker ps
  - curl localhost:11212
  - python elasticache_auto_discovery/__init__.py "localhost:11212"

after_script:
  - docker-compose down
