language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - docker-compose up --build -d

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python /elasticache_auto_discovery/__init__.py

after_script:
  - docker-compose down